# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-13

    steps:
    
    #Ensure the xcode version is available
    - name: List Xcode installations
      run: sudo ls -1 /Applications | grep "Xcode"
    
    - name: Xcode Setup
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'
        
    - uses: actions/checkout@v4
        
    - name: setup-cocoapods
      uses: maxim-lobanov/setup-cocoapods@v1
      with:
        version: 1.15.2

    - uses: actions/cache@v2
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
          
    - name: CocoaPod Install
      run: pod install
       
    - name: SwiftFormat
      run: swiftformat . --lint
        
    - name: SwiftLint
      run: swiftlint lint --strict

#    - name: Build a project without cocoapods
#      run: |
#        xcodebuild build -project MeditationAppUI.xcodeproj -scheme MeditationAppUI clean build -sdk iphoneos CODE_SIGNING_ALLOWED=No

#    - name: Run tests
#      run: |
#        xcodebuild test -project MeditationAppUI.xcodeproj -scheme MeditationAppUI clean build -sdk iphoneos -destination "platform=iOS Simulator,OS=17.2,name=iPhone 14 Pro Max" CODE_SIGNING_ALLOWED=No

#    - name: Build a workspace with cocoapods
#      run: |
#        xcodebuild build -project MeditationAppUI.xcodeproj -scheme MeditationAppUI clean build -sdk iphoneos CODE_SIGNING_ALLOWED=No

#    - name: Clean and build a workspace with cocoapods in Debug
#      run: |
#        xcodebuild -workspace MeditationAppUI.xcworkspace -scheme MeditationAppUI clean build -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15' CODE_SIGNING_ALLOWED=No


    - name: Build a workspace with cocoapods in Debug
      run: |
        xcodebuild -workspace MeditationAppUI.xcworkspace -scheme MeditationAppUI build -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15' CODE_SIGNING_ALLOWED=No

#    - name: Test
#      run: xcodebuild test -workspace MeditationAppUI.xcworkspace -scheme MeditationAppUI -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15'
