# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4
    
    - name: Xcode Setup
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.3.1'

    - name: Build
      run: |
        xcodebuild build -project MeditationAppUI.xcodeproj -scheme MeditationAppUI clean build -sdk iphoneos CODE_SIGNING_ALLOWED=No

    - name: Build and Test
      run: |
        xcodebuild \
         -project MeditationAppUI.xcodeproj \
         -scheme MeditationAppUI \
         -sdk iphonesimulator \
         -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.1' \
         test || exit 1
