# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-13

    steps:
    
    #Ensure the xcode version is available
    - name: List Xcode installations
      run: sudo ls -1 /Applications | grep "Xcode"
    
    - uses: actions/checkout@v4
    
    - name: Xcode Setup
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'
       
    - name: SwiftFormat
      run: swiftformat . --lint
        
    - name: SwiftLint
      run: swiftlint lint --strict

    - name: Build only a project
      run: |
        xcodebuild build -project MeditationAppUI.xcodeproj -scheme MeditationAppUI clean build -sdk iphoneos CODE_SIGNING_ALLOWED=No
        
    #- name: Run tests
      #run: |
        #xcodebuild test -project MeditationAppUI.xcodeproj -scheme MeditationAppUI clean build -sdk iphoneos -destination "platform=iOS Simulator,OS=17.2,name=iPhone 14 Pro Max" CODE_SIGNING_ALLOWED=No
        
    - name: Build a workspace with cocoapods
      run: |
        xcodebuild build -project MeditationAppUI.xcodeproj -scheme MeditationAppUI clean build -sdk iphoneos CODE_SIGNING_ALLOWED=No
